plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.r2g.springdemo'
version = '1.0.0'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

/*dependencies {



	implementation 'org.springframework.boot:spring-boot-starter-batch'
	implementation 'org.springframework.batch:spring-batch-core:5.0.1'
implementation 'org.springframework:spring-core:5.3.0'
	// Spring Framework Core
    implementation 'org.springframework:spring-core:6.1.0'
    //implementation 'org.springframework:spring-context:6.1.0'
	
	
	runtimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test:3.0.0'
	implementation 'org.springframework.batch:spring-batch-test:5.0.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
//	implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.24.3'
//	// https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
//	implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.24.3'
//	
	
}*/




dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-batch'
//	runtimeOnly 'org.hsqldb:hsqldb'
//	runtimeOnly 'mysql:mysql-connector-j'
	// https://mvnrepository.com/artifact/mysql/mysql-connector-java
	implementation 'mysql:mysql-connector-java:8.0.33'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.batch:spring-batch-test'
	implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.24.3'
	implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.24.3'
}


tasks.named('test') {
	useJUnitPlatform()
}
