# Root logger configuration
#rootLogger.level=INFO
#rootLogger.appenderRefs=consoleAppender, rootFileAppender, myAppFileAppender
## Console appender for the root logger
#appender.consoleAppender.type=Console
#appender.consoleAppender.name=consoleAppender
#appender.consoleAppender.layout.type=PatternLayout
#appender.consoleAppender.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n
## File appender for the root logger
#appender.rootFileAppender.type=File
#appender.rootFileAppender.name=rootFileAppender
#appender.rootFileAppender.fileName=C:/logs/root.log
#appender.rootFileAppender.layout.type=PatternLayout
#appender.rootFileAppender.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n
#appender.rootFileAppender.append=true
appenders=myAppFileAppender
# File appender for com.example.myapp
appender.myAppFileAppender.type=File
appender.myAppFileAppender.name=myAppFileAppender
appender.myAppFileAppender.fileName=logs/appserver.log
appender.myAppFileAppender.layout.type=PatternLayout
appender.myAppFileAppender.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n
appender.myAppFileAppender.append=true
loggers=myAppLogger,utilsLogger
# Logger for com.example.myapp package (logs to a file only)
logger.myAppLogger.name=com.roadtoglory.ds.testing
logger.myAppLogger.level=DEBUG
logger.myAppLogger.additivity=false
logger.myAppLogger.appenderRefs=myAppFileAppender
# Logger for com.example.utils package (logs to console only)
logger.utilsLogger.name=com.roadtoglory.ds.recursion
logger.utilsLogger.level=INFO
logger.utilsLogger.additivity=false
logger.utilsLogger.appenderRefs=myAppFileAppender
